
version: 2


sources:
  - name: base
    tables:
        - name: customer
        - name: order
        - name: payment

# models:
#     - name: customer
#       description: "A person who bought stuff from us"
#       columns:
#           - name: id
#             description: "The primary key for this table"
#             tests:
#                 - unique
#                 - not_null
#           - name: name
#             description: "The customer's name"
#             tests:
#                 - not_null


