
version: 2


models:
  - name: payment_types
    description: "Count of payments by type"
    columns:
      - name: payment_type
        description: "Type of payment being counted"
      - name: payment_count
        description: "Count of this payment type"

  - name: order_payments
    description: "Report showing orders vs payments"
    columns:
      - name: order_id
        description: "PK from order table"
      - name: customer_id
        description: "FK to customer table"
      - name: order_total
        description: "Total cost of order"
      - name: payment_total
        description: "Total payment for order"
      - name: amount_remaining
        description: "Remaining money to be paid for this order"

  - name: customer_payments
    description: "Report showing payment of all a customer's orders"
    columns:
      - name: customer_id
        description: "PK from customer table"
      - name: customer_name
        description: "Name of customer"
      - name: total_owed
        description: "Total order amount"
      - name: total_paid
        description: "Total amount paid"
      - name: account_balance
        description: "Remaining balence on account"
